In [1]:
from legacy_static import *
import pandas as pd
import scipy.io
import matplotlib.pyplot as plt
from PIL import Image, ImageOps
import random

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [2]:
def convert_edge_v3(fi,save, factor=2.5):
    # 1: detect edges using Stefan Pitur's implementation

    cv2_img = DetectEdges(fi)
    original_img = Image.fromarray(cv2.imread(fi)).convert("L")
    
    pil_img = Image.fromarray(cv2_img).convert("L")

    # 2: Resize
    width, height = pil_img.size
    scale = width / (factor*500)
    width, height = width / scale, height / (scale*2)
    width, height = int(width), int(height)

    # final = ImageOps.invert(pil_img)
    final = pil_img
    final = final.resize((width,height))

    original_img = original_img.resize((width,height))
    # final.show()      
    
    # 3: Convert to 0s and 1s for bnw
    img_array_edges = np.array(final)
    original_img = np.array(original_img)
    fin = ""

    # SAVING TRAIN DATA
    data = []
    labels = []
    counter = 0

    # 4: Take 10x10 tiles and replace with ASCII character
    inc = 10
    for li in range(0,math.floor(len(img_array_edges) / inc) * inc,inc): #Floor function to use only even bounds. 
    #     Odd bounds have data loss on last col/row
        for i in range(0,math.floor(len(img_array_edges[li]) / inc) * inc,inc):
            # Subsetting the tile itself
            subs = []
            subs.append([xi[i:i+inc] for xi in img_array_edges[li:li+inc]])
            subs = np.array(subs)

            subs_og = []
            subs_og.append([xi[i:i+inc] for xi in img_array_edges[li:li+inc]])
            subs_og = np.array(subs_og)
            # checking the minimum distance between each character vector and tile vector
            min = 0
            min_dist = np.linalg.norm(edge_vectors3[0]-subs.flatten())
            if not (np.all(subs == 0)):
                for j in range(0,len(edge_vectors3)):
                    new_mind_dist = np.linalg.norm(edge_vectors3[j]-subs.flatten())

                    if (new_mind_dist<min_dist):
                        min = j
                        min_dist = new_mind_dist
            
            # SAVING TRAIN DATA
            # if counter < 100000
            data.append(subs_og[0])
            labels.append(min)

            

            fin = fin + chr(min+32)
        fin = fin + '\n'

    # Normalize data
    data = np.array(data)
    labels = np.array(labels)
    data = data / 255.0
    data = data.reshape((len(data), 10, 10, 1))  # (num_samples, height, width, channels)
    flattened_images = data.reshape(data.shape[0], -1)
    reshaped_data = np.concatenate((labels.reshape(-1, 1).astype(np.int8), flattened_images.astype(np.float64)), axis=1)

    # Define column names
    # pixel_column_names = ['pixel{}'.format(i) for i in range(1, reshaped_data.shape[1])]
    # column_names = ["label"] + pixel_column_names

    # Convert reshaped_data to a DataFrame with specified column names and dtypes
    df = pd.DataFrame(reshaped_data)

    # # Convert label column to int8 dtype
    # df['label'] = df['label'].astype(np.int8)

    # # Convert pixel columns to float64 dtype
    # for col in pixel_column_names:
    #     df[col] = df[col].astype(np.float64)

    df = df.reset_index(drop=True)
    df.to_csv('archive/ascii_character_classification_sanrio_data_raw.csv', mode='a', header=None, index=False)

    
    # 5: Output to terminal
    # print(fin)
    # 6: Save to output file
    if(save):
        with open(save,'w') as f:
            f.write(fin)

In [3]:
# path = "C:\\Users\\Sai\\Work\\Transformer\\data"
#  Source: Google Quickdraw
# path = "anime_pics"
# Source: https://www.kaggle.com/datasets/prasoonkottarathil/gananime-lite
path = "Logos"
# Source: https://www.kaggle.com/datasets/kkhandekar/popular-brand-logos-image-dataset?select=Logos
path = "Sanrio/sanrio-images/images"
# Source: https://www.kaggle.com/datasets/vnxiclaire/sanrio-character-image-dataset/data
# path = "data/images"
for f in os.listdir(path):
    print(f)
    random_number = random.uniform(1, 3)
    convert_edge_v3(os.path.join(path,f), save=False, factor=random_number)

if not os.path.exists(path):
    print(f"Path '{path}' does not exist.")
    
# else:
#     counter = 0
#     for f in os.listdir(path):
#         counter+=1
#         if counter > 0:
#             print(f"Files Processed: {counter}")
#             file_path = os.path.join(path, f)
#             if os.path.isfile(file_path):
#                 cv2_img = DetectEdges(file_path)
#                 if cv2_img.dtype is not None:
#                     pil_img = Image.fromarray(cv2_img).convert("L")
#                     pil_img.save(os.path.join("EdgeMaps", f))
#                 else:
#                     print(f"Error processing '{file_path}'.")
#             else:
#                 print(f"'{file_path}' is not a file.")


02_nobunyan_a.png
03_yukinyan_a.png
04_datenyan_a.png
05_nyanbee_a.png
06_keijironyan_a.png
07_kenshinnyan_a.png
08_shingennyan_a.png
09_imanyan_a.png
10_nyanbu_a.png
11_jibunyan_a.png
12_nyanrin_a.png
13_nyanba_a.png
14_kiyomanya_a.png
15_chousokabenyan_a.png
16_iepon_a.png
accyangaichiban_b.png
aggressiveretsuko_b.png
aggressiveretsuko_sub_02.png
aggressiveretsuko_sub_03.png
aggressiveretsuko_sub_04.png
aggressiveretsuko_sub_05.png
aggressiveretsuko_sub_06.png
aggressiveretsuko_sub_07.png
aggressiveretsuko_sub_08.png
aggressiveretsuko_sub_09.png
aggressiveretsuko_sub_10.png
aggressiveretsuko_sub_11.png
aggressiveretsuko_sub_12.png
aggressiveretsuko_sub_13.png
aggressiveretsuko_sub_14.png
aggressiveretsuko_sub_15.png
aggressiveretsuko_sub_16.png
aggressiveretsuko_sub_17.png
aggressiveretsuko_sub_18.png
aggressiveretsuko_sub_19.png
aggressiveretsuko_sub_20.png
aggressiveretsuko_sub_21.png
aggressiveretsuko_sub_22.png
aggressiveretsuko_sub_23.png
aggressiveretsuko_sub_24.png
aggressiver

In [5]:
df = pd.read_csv("archive/ascii_character_classification_sanrio_data_raw.csv")

In [ ]:
df.head()

,label,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,pixel9,...,pixel91,pixel92,pixel93,pixel94,pixel95,pixel96,pixel97,pixel98,pixel99,pixel100
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
